### ISSUE TITLE
It seems that only hlds.exe is missing

### ISSUE THREAD

**Issue by juaniio** [Zeromix9/Server-Creation-Tool#2]
Hi,

Both this tool and the original approach using `steamcmd` manually from console seem to work (after running it more than once because of the known steamcmd bug with the HL server).

However, the only file missing seems to be `hlds.exe`. All other files seem to have been downloaded (the downloaded directory is about 730MB).

I tried to copy and paste the hlds.exe from my original CS Steam installation directory to the dedicated server directory created with steamcmd, but when I run the file (console, even adding `-game cstrike`, or directly by double-click) it doesn't work, with error like "image is corrupted".

Thanks for any advice.

**Comment by Zeromix9** [comment]
Hello there,
sorry, that i didn´t saw this post earlier.

To see, if I could reproduce this error, i deleted all my CS 1.6 Server files and downloaded them again through the tool.

The first time I got an error, the hlds.exe, was there.
Then i restarted this download, this time it finished without any errors, and so it seems that all files were downloaded correcly.

![Unbenannt](https://user-images.githubusercontent.com/21269784/83327180-48d74a00-a27a-11ea-9308-90ced06359f0.png)
