### ISSUE TITLE
Has it been tested on Linux?

### ISSUE THREAD

**Issue by iP2-Rune** [Zeromix9/Server-Creation-Tool#3]
Does this run on linux or has it been tested with Wine or Playonlinux yet I'm wondering if it would work with linux so this tool automates the dedicated server install for CS:S etc?

**Comment by SteliosLL** [comment]
> Does this run on linux or has it been tested with Wine or Playonlinux yet I'm wondering if it would work with linux so this tool automates the dedicated server install for CS:S etc?

it hasn't been tested on linux

**Comment by Zeromix9** [comment]
Exacly. I didn´t test it on Linux.
